services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env.local
    volumes:
      - ./api/app:/app/app
      - ./trained_model:/app/trained_model
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: diabetes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
